name: golos-inventory

services:
  app:
    image: toothiertrain13/golos-app:latest
    container_name: golos-app
    restart: unless-stopped
    env_file:
      - .env                          # ← toda la config viene de aquí
    ports:
      - "8000:8000"
    networks:
      - red_ingenieria
    command:
      - gunicorn
      - --bind
      - 0.0.0.0:8000
      - --workers
      - "2"
      - --timeout
      - "120"
      - --worker-tmp-dir
      - /dev/shm
      - --pythonpath
      - config
      - config.wsgi:application
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/admin/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  red_ingenieria:
    external: true
