"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env.local file
load_dotenv('.env.local')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-key-change-this')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inventory',
    'rest_framework',
    'corsheaders',
    'drf_spectacular',
    'rest_framework_simplejwt',
    'django_filters',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database - SQLite for local development
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# CORS settings for local development
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8080",
    "http://127.0.0.1:8080",
]

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True

# DRF Spectacular settings
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'config.exceptions.custom_exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'PREPROCESSING_HOOKS': [],
    'POSTPROCESSING_HOOKS': ['config.urls.postprocess_jwt_tags'],
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Golos Inventory API',
    'DESCRIPTION': 'Sistema de gestión de inventario para productos y ventas con optimización de imágenes y control de stock',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
        'filter': True,
        'showExtensions': True,
        'showCommonExtensions': True,
        'docExpansion': 'none',
        'defaultModelsExpandDepth': 2,
        'defaultModelExpandDepth': 2,
    },
    'REDOC_UI_SETTINGS': {
        'hideHostname': True,
        'hideDownloadButton': False,
        'expandResponses': '200,201',
        'hideLoading': True,
    },
    'ENUM_NAME_OVERRIDES': {
        'GenderEnum': ['ProductVariant.gender'],
        'MovementTypeEnum': ['MovementInventory.movement_type'],
        'SaleStatusEnum': ['Sale.status'],
    },
    'TAGS': [
        {
            'name': 'Authentication',
            'description': 'Autenticación JWT y gestión de tokens'
        },
        {
            'name': 'Users',
            'description': 'Gestión de usuarios y grupos del sistema'
        },
        {
            'name': 'Groups',
            'description': 'Gestión de grupos con permisos'
        },
        {
            'name': 'Sales',
            'description': 'Gestión de ventas y confirmación de pedidos'
        },
        {
            'name': 'SalesReturns',
            'description': 'Gestión de devoluciones de ventas'
        },
        {
            'name': 'SalesDetails',
            'description': 'Gestión de detalles de ventas'
        },
        {
            'name': 'Products',
            'description': 'Catálogo de productos y variantes con control de stock'
        },
        {
            'name': 'ProductsVariants',
            'description': 'Variantes de productos (colores, tallas, etc.)'
        },
        {
            'name': 'ProductsImages',
            'description': 'Imágenes de productos con metadatos '
        },
        {
            'name': 'Inventory',
            'description': 'Movimientos de inventario y historial completo'
        },
        {
            'name': 'InventoryHistory',
            'description': 'Historial de inventario (solo lectura)'
        },
        {
            'name': 'InventoryReportDaily',
            'description': 'Reporte diario de inventario (solo lectura)'
        },
        {
            'name': 'InventorySnapshots',
            'description': 'Snapshots mensuales de inventario (solo lectura)'
        },
        {
            'name': 'InventoryCloseMonth',
            'description': 'Cierre mensual de inventario'
        },
        {
            'name': 'InventoryAdjustments',
            'description': 'Ajustes manuales de inventario (controlado)'
        },
        {
            'name': 'Batch',
            'description': 'Operaciones masivas'
        },
        {
            'name': 'Suppliers',
            'description': 'Gestión de proveedores'
        },
        {
            'name': 'SuppliersReturns',
            'description': 'Gestión de devoluciones a proveedores'
        },
        {
            'name': 'Dashboard',
            'description': 'Dashboard de estadísticas y métricas'
        },
        {
            'name': 'Export',
            'description': 'Exportaciones de datos'
        },
        {
            'name': 'Notifications',
            'description': 'Gestión de notificaciones (solo lectura)'
        },
        {
            'name': 'Purchase',
            'description': 'Gestión de compras'
        }
    ],
}

# Email backend for development (console)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Backblaze B2 Storage Configuration
AWS_ACCESS_KEY_ID = os.getenv('BACKBLAZE_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('BACKBLAZE_APPLICATION_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('BACKBLAZE_BUCKET_NAME')
AWS_S3_ENDPOINT_URL = os.getenv('BACKBLAZE_ENDPOINT')
AWS_S3_REGION_NAME = os.getenv('BACKBLAZE_REGION')
AWS_S3_CUSTOM_DOMAIN = None
AWS_DEFAULT_ACL = 'private'
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',  # Cache por 1 día
}

# Usar Backblaze para archivos de media (imágenes)
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
