# Generated by Django 6.0.1 on 2026-01-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementinventory',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('return', 'Return')], max_length=50),
        ),
        migrations.AlterField(
            model_name='movementinventory',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
