# Generated by Django 6.0.1 on 2026-02-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_movementinventory_movement_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Texto alternativo para SEO y accesibilidad', max_length=200),
        ),
        migrations.AddField(
            model_name='productimage',
            name='file_size',
            field=models.IntegerField(blank=True, editable=False, help_text='Tamaño del archivo en bytes (autocompletado)', null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='height',
            field=models.IntegerField(blank=True, editable=False, help_text='Alto en píxeles (autocompletado)', null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Marcar como imagen principal del producto'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='width',
            field=models.IntegerField(blank=True, editable=False, help_text='Ancho en píxeles (autocompletado)', null=True),
        ),
    ]
