# Generated by Django 6.0.1 on 2026-02-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_productimage_alt_text_productimage_file_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('entity', models.CharField(max_length=100)),
                ('entity_id', models.PositiveIntegerField()),
                ('performed_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='movementinventory',
            options={'permissions': [('manage_inventory', 'Can manage inventory')]},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('confirm_sale', 'Can confirm sales'), ('manage_inventory', 'Can manage inventory')]},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'permissions': [('confirm_sale', 'Can confirm sales')]},
        ),
        migrations.AlterField(
            model_name='movementinventory',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Compra'), ('sale_out', 'Salida por venta'), ('sale_return', 'Devolución de venta'), ('adjustment', 'Ajuste'), ('return', 'Devolución proveedor')], max_length=20),
        ),
    ]
