# Generated by Django 6.0.1 on 2026-02-08 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auditlog_alter_movementinventory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('stock_opening', models.IntegerField()),
                ('total_in', models.IntegerField()),
                ('total_out', models.IntegerField()),
                ('stock_closing', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='inventory.productvariant')),
            ],
            options={
                'ordering': ['-month', 'variant'],
                'unique_together': {('month', 'variant')},
            },
        ),
    ]
