# Generated by Django 6.0.1 on 2026-02-08 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventorysnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('nit', models.CharField(blank=True, max_length=20, null=True)),
                ('average_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio promedio de sus productos', max_digits=10, null=True)),
                ('last_purchase_date', models.DateField(blank=True, help_text='Última fecha de compra', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=50)),
                ('preferred_products', models.ManyToManyField(blank=True, help_text='Productos que este proveedor suele vender', related_name='suppliers', to='inventory.product')),
            ],
            options={
                'ordering': ['-last_purchase_date', 'name'],
                'permissions': [('manage_suppliers', 'Can manage suppliers')],
            },
        ),
        migrations.AddField(
            model_name='movementinventory',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Proveedor (para compras y devoluciones)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.supplier'),
        ),
    ]
