# Generated by Django 5.1.5 on 2026-02-14 03:29

import django.db.models.deletion
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_supplier_movementinventory_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='inventory.productvariant'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Imagen del producto almacenada en Backblaze', storage=storages.backends.s3.S3Storage(), upload_to='products/'),
        ),
    ]
