# Generated by Django 5.1.5 on 2026-02-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_productvariant_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('sneakers', 'Tenis'), ('heels', 'Tacones'), ('classics', 'Clásicos'), ('boots', 'Botas'), ('sandals', 'Sandalias'), ('flats', 'Planas'), ('loafers', 'Mocasines'), ('other', 'Otro')], default='sneakers', help_text='Tipo de producto (especialmente para zapatos)', max_length=20),
        ),
    ]
