# Generated by Django 5.1.5 on 2026-02-14 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementinventory',
            name='sale',
            field=models.ForeignKey(blank=True, help_text='Venta relacionada (para salidas y devoluciones)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='inventory.sale'),
        ),
    ]
