# Generated by Django 5.1.5 on 2026-02-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_sale_canceled_at_sale_confirmed_at_sale_delivered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Mi Tienda', max_length=120)),
                ('tagline', models.CharField(blank=True, default='', max_length=180)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('hero_title', models.CharField(blank=True, default='', max_length=140)),
                ('hero_subtitle', models.CharField(blank=True, default='', max_length=220)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='system', max_length=50)),
            ],
            options={
                'verbose_name': 'Store Branding',
                'verbose_name_plural': 'Store Branding',
            },
        ),
    ]
