# Generated by Django 5.1.5 on 2026-02-26 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_storebranding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(max_length=60)),
                ('service', models.CharField(max_length=60)),
                ('tracking_number', models.CharField(max_length=80, unique=True)),
                ('provider_reference', models.CharField(blank=True, max_length=120, null=True)),
                ('label_url', models.URLField(blank=True, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='COP', max_length=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='created', max_length=20)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='store_api', max_length=50)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='inventory.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_event_id', models.CharField(max_length=120, unique=True)),
                ('event_type', models.CharField(max_length=60)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='inventory.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
