# Generated by Django 5.1.5 on 2026-02-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_sale_payment_method_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebranding',
            name='legal_contact_address',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AddField(
            model_name='storebranding',
            name='legal_contact_city',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='storebranding',
            name='legal_contact_department',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='storebranding',
            name='legal_contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='storebranding',
            name='legal_contact_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='storebranding',
            name='legal_id_number',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='storebranding',
            name='legal_id_type',
            field=models.CharField(blank=True, default='NIT', max_length=20),
        ),
        migrations.AddField(
            model_name='storebranding',
            name='legal_representative_name',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
    ]
