# Generated by Django 5.1.5 on 2026-02-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_storebranding_legal_contact_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebranding',
            name='promo_bottom_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storebranding',
            name='promo_bottom_text',
            field=models.CharField(blank=True, default='', max_length=260),
        ),
        migrations.AddField(
            model_name='storebranding',
            name='promo_bottom_title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='storebranding',
            name='promo_top_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storebranding',
            name='promo_top_text',
            field=models.CharField(blank=True, default='', max_length=260),
        ),
        migrations.AddField(
            model_name='storebranding',
            name='promo_top_title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
