# Generated by Django 5.1.5 on 2026-02-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_storebranding_promo_bottom_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebranding',
            name='promo_top_image_desktop_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='storebranding',
            name='promo_top_image_mobile_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
