# Generated by Django 5.1.5 on 2026-02-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_storebranding_promo_top_image_desktop_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebranding',
            name='favicon_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
