# Generated by Django 5.1.5 on 2026-03-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_storebranding_favicon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='commercial_metadata',
            field=models.JSONField(blank=True, help_text='Datos comerciales internos (costos de envío proyectado, fees de pasarelas, márgenes) calculados al checkout.', null=True),
        ),
    ]
