# Generated by Django 5.1.5 on 2026-03-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_sale_commercial_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebranding',
            name='hero_image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
