# Generated by Django 5.1.5 on 2026-03-14 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_storebranding_hero_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('opened_by', models.CharField(max_length=50)),
                ('initial_balance', models.DecimalField(decimal_places=2, help_text='Base de caja al abrir', max_digits=12)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Balance esperado según sistema', max_digits=12, null=True)),
                ('actual_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Dinero físico contado', max_digits=12, null=True)),
                ('difference', models.DecimalField(blank=True, decimal_places=2, help_text='Diferencia entre esperado y real', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada')], default='open', max_length=10)),
            ],
            options={
                'verbose_name': 'Sesión de Caja',
                'verbose_name_plural': 'Sesiones de Caja',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_income', models.BooleanField(default=False, help_text='True si es una categoría de ingreso, False si es egreso')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría Financiera',
                'verbose_name_plural': 'Categorías Financieras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Egreso')], max_length=10)),
                ('description', models.TextField()),
                ('payment_method', models.CharField(default='cash', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.financialcategory')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='inventory.sale')),
                ('session', models.ForeignKey(blank=True, help_text='Sesión de caja a la que pertenece este movimiento (opcional si es bancario)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.cashsession')),
            ],
            options={
                'verbose_name': 'Transacción Financiera',
                'verbose_name_plural': 'Transacciones Financieras',
                'ordering': ['-created_at'],
            },
        ),
    ]
