# Generated by Django 5.1.5 on 2026-03-15 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_cashsession_financialcategory_financialtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='document_number',
            field=models.CharField(blank=True, help_text='Número consecutivo legal (PRE-001, SETT-123, etc.)', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice_required',
            field=models.BooleanField(default=False, help_text='Indica si el cliente solicitó factura electrónica'),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_electronic_invoice',
            field=models.BooleanField(default=False, help_text='True si este documento fue emitido como Factura Electrónica ante la DIAN'),
        ),
        migrations.CreateModel(
            name='ElectronicInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='ID interno del proveedor de facturación', max_length=100, unique=True)),
                ('number', models.CharField(help_text='Número de factura (ej: SETT-1234)', max_length=40)),
                ('cufe', models.CharField(blank=True, help_text='Código Único de Factura Electrónica', max_length=120, null=True)),
                ('qr_data', models.TextField(blank=True, help_text='Contenido del código QR legal', null=True)),
                ('pdf_url', models.URLField(blank=True, help_text='Link al PDF oficial del proveedor', null=True)),
                ('xml_url', models.URLField(blank=True, help_text='Link al XML legal', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('accepted', 'Aceptado por DIAN'), ('rejected', 'Rechazado por DIAN'), ('failed', 'Error de Comunicación')], default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('dian_response_at', models.DateTimeField(blank=True, null=True)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_invoice', to='inventory.sale')),
            ],
            options={
                'verbose_name': 'Factura Electrónica',
                'verbose_name_plural': 'Facturas Electrónicas',
                'ordering': ['-created_at'],
            },
        ),
    ]
