# Generated by Django 5.1.5 on 2026-03-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_sale_document_number_sale_invoice_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='invoicing_method',
            field=models.CharField(choices=[('NONE', 'Solo Tiquete POS'), ('AUTOMATIC', 'Automático (Factus)'), ('MANUAL', 'Manual (Portal DIAN)')], default='NONE', help_text='Método preferido para la emisión de la factura', max_length=20),
        ),
    ]
