# Generated by Django 5.1.5 on 2026-03-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_sale_invoicing_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebranding',
            name='maintenance_message',
            field=models.TextField(blank=True, default='Estamos mejorando nuestra tienda para ti. Volveremos pronto.', help_text='Mensaje que verán los clientes cuando la tienda esté en mantenimiento'),
        ),
        migrations.AddField(
            model_name='storebranding',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text="Activa la página de 'Estamos trabajando en el sitio'"),
        ),
    ]
